export enum ERRORS_ENUM {
  AUTHENTICATION_ERROR_INVALID_CREDENTIALS = 'AUTHENTICATION_ERROR_INVALID_CREDENTIALS',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_ERROR_FIELD_REQUIRED = 'VALIDATION_ERROR_FIELD_REQUIRED',
  VALIDATION_ERROR_NOT_A_BOOLEAN = 'VALIDATION_ERROR_NOT_A_BOOLEAN',
  VALIDATION_ERROR_NOT_A_STRING = 'VALIDATION_ERROR_NOT_A_STRING',
  VALIDATION_ERROR_STRING_NOT_LONG_ENOUGH = 'VALIDATION_ERROR_STRING_NOT_LONG_ENOUGH',
  VALIDATION_ERROR_INVALID_EMAIL = 'VALIDATION_ERROR_INVALID_EMAIL',
  VALIDATION_ERROR_INVALID_PASSWORD = 'VALIDATION_ERROR_INVALID_PASSWORD',
  VALIDATION_ERROR_NO_SUCH_RECORD = 'VALIDATION_ERROR_NO_SUCH_RECORD',
}
